version: "3"

services:
  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    networks:
      - nj
    volumes:
      - data-db:/var/lib/mysql/data
    environment:
      POSTGRES_PASSWORD: admin@000
      POSTGRES_USER: admin
      POSTGRES_DB: notejam

  web:
    image: notejam
    container_name: notejam
    command: bash -c "python manage.py syncdb && python manage.py migrate &&  manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    networks:
      - nj
    depends_on:
      - db


volumes:
  data-db:
    
networks:
  nj:
